version: '3'
services:
  calc:
    container_name: taxi_api
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.calc
    ports:
      - "9090:9090"
    restart: on-failure
    depends_on:
      - db
    links:
      - db
      - requester
  db:
    image: "postgres:latest"
    container_name: "taxi_db"
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "taxi_db"
    volumes:
       #- $HOME/docker/volumes/psql_data/taxi:/var/lib/postgresql/data
  requester:
    container_name: taxi_requester
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.requester
    restart: on-failure
    environment:
      TAXI_ORS_TOKEN: !!! insert token here !!!
      TAXI_BING_TOKEN: !!! insert token here !!!
