name: build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Build calc package
        run: |
          go build -o /dev/null ./calc/cmd/main.go
      - name: Build requester package
        run: |
          go build -o /dev/null ./requester/cmd/main.go
